version: '3'

services:
  master:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: vertex-locust:0.1
    ports:
     - "8089:8089"
    volumes:
      - ./:/home/locust
    command: -f /home/locust/locustfile.py --master -H https://{region}-aiplatform.googleapis.com --headless --expect-workers 4 -u 16 -r 1 -t 300 -s 1 --html=/home/locust/result.html --logfile /home/locust/locust.log
  
  worker:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: vertex-locust:0.1
    volumes:
      - ./:/home/locust
    command: -f /home/locust/locustfile.py --worker --master-host master